Repository randovania/mercury-engine-data-structures, pull requests merged in 2024-07, with the labels that each got.

#149 Update bmssd sg fields for MSR
  src/mercury_engine_data_structures/formats/bmssd.py
  tests/formats/test_bmssd.py
Labels: game: Metroid: Samus Returns

#153 Updated README with all formats
  README.md
  src/mercury_engine_data_structures/formats/blsnd.py
  tests/formats/test_blsnd.py
Labels: documentation

#152 Adds BMSEM support
  src/mercury_engine_data_structures/formats/__init__.py
  src/mercury_engine_data_structures/formats/bmsem.py
  tests/formats/test_bmsem.py
Labels: enhancement, game: Metroid: Samus Returns

#151 MSR - Add support to bmdefs
  src/mercury_engine_data_structures/formats/__init__.py
  src/mercury_engine_data_structures/formats/bmdefs.py
  tests/formats/test_bmdefs.py
Labels: game: Metroid: Samus Returns

#188 MSR - Fix wrong minor version for bmscc
  src/mercury_engine_data_structures/formats/bmscc.py
Labels: game: Metroid: Samus Returns

#191 Added Samus Returns property names
  src/mercury_engine_data_structures/sr_property_names.json
Labels: game: Metroid: Samus Returns

#192 added BLUT (Binary LookUp Table?)
  README.md
  src/mercury_engine_data_structures/formats/__init__.py
  src/mercury_engine_data_structures/formats/blut.py
  tests/formats/test_blut.py
Labels: game: Metroid Dread

#193 Added BMSSH format
  README.md
  src/mercury_engine_data_structures/formats/gui_files.py
  tests/formats/test_gui.py
Labels: game: Metroid Dread

#194 BMSAT
  README.md
  src/mercury_engine_data_structures/formats/__init__.py
  src/mercury_engine_data_structures/formats/bmsat.py
  tests/formats/test_bmsat.py
Labels: game: Metroid Dread

#195 BGSNDS
  README.md
  src/mercury_engine_data_structures/formats/__init__.py
  src/mercury_engine_data_structures/formats/bgsnds.py
  tests/formats/test_bgsnds.py
Labels: game: Metroid Dread

#196 Added bnvib
  README.md
  src/mercury_engine_data_structures/formats/__init__.py
  src/mercury_engine_data_structures/formats/bnvib.py
  tests/formats/test_bnvib.py
Labels: game: Metroid Dread
